## a non caching full recursive resolver config for bind
## runs on the same machine as web-dig

acl "trusted" {
    localhost;
    localnets;          
};

options {
    directory "/var/cache/bind";

    # allow full recursion
    recursion yes;

    # ACLs
    allow-recursion { trusted; };
    allow-query-cache { trusted; }; 

    # disable cache
    max-cache-ttl 0;
    max-ncache-ttl 0;
    max-cache-size 1M;
    cleaning-interval 1;

    # no forwarding!!!
    forwarders {};

    # DNSSEC validation on
    dnssec-validation auto;    # oder yes (empfohlen)
    auth-nxdomain no;          # RFC-konform
    listen-on port 53 { 127.0.0.1; };
    listen-on-v6 port 53 { ::1; };
    version "hidden";
};
